name: update-stats

on:
  # schedule:
  #   - cron: '0 0 * * 0' # 毎週日曜日の午前0時に実行
  workflow_dispatch:
  push: #テスト

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.6'
      
      - name: Generate Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/syamasaw/go-readme-stats@latest
          go run ./cmd/main.go -x=Kotlin,PHP,HTML,CSS,PLpgSQL > stats.txt
          cat stats.txt
